ADMIN_EMAIL: support@FounderDigest.com
COMPANY_NAME: FounderDigest
POSTMARK_API_TOKEN: xxxx-yyy-zzzz
development:
  BASE_URL: http://localhost:3000
  STRIPE_SECRET_KEY: sk_test_51Nd91YI2zBStTvQb5QcIrrSDlxQxJUQxDbLIQy5t2LYGUZFyMJKcWPmMjTgKggQdHsFfuVYpScwTbv5cAa8xIEDQ000uRJZIBQ
  STRIPE_PRODUCT_PRICE_ID: price_1NexwVI2zBStTvQb9yVXfjbi
production:
  BASE_URL: https://FounderDigest.com
  STRIPE_SECRET_KEY: sk_live_asdfasdfasdf
  STRIPE_PRODUCT_PRICE_ID: price_1asdfasdf
